### ISSUE TITLE
[BUG] deletehash property in AlbumData

### ISSUE THREAD

**Issue by ArielGavrielov** [KenEucker/imgur#210]
**Describe the bug**
`
Property 'deletehash' does not exist on type 'AlbumData'.
TypeScript Error.
`

**To Reproduce**
`
const album = await imgur.createAlbum('Test');
imgur.upload({
    image: stream,
    type: 'stream',
    album: album.data.deletehash
})
`

**Expected behavior**
Get album deletehash from API. (In JS it works perfectly)

**Environment (please complete the following information):**
 - Library version [e.g. 1.0.0]: 2.2.0
 - OS [e.g. macOS]: macOS
 - NodeJS version [e.g.14.16.0]: v16.13.0

**Additional context**
Add deletehash property in AlbumData

**Comment by franva** [comment]
Has this been updated? I'm facing the similar issue. I might need deletehash for add images to album.

I actually want to add an image to my own album, but cannot find a way to do it.

**Comment by KenEucker** [comment]
@franva you do not need a deleteHash to add to an album. You simply need to supply the album hash when calling upload:

```
...
const album = 'your-album-hash'
imgur.upload({ image, album })
```

**Comment by franva** [comment]
> @franva you do not need a deleteHash to add to an album. You simply need to supply the album hash when calling upload:
> 
> ```
> ...
> const album = 'your-album-hash'
> imgur.upload({ image, album })
> ```

Hi @KenEucker  thank you for your reply.

I actually have that, please see the details of my code here:
https://stackoverflow.com/questions/77889717/how-to-add-an-uploaded-image-to-my-own-imgur-album

**Comment by franva** [comment]
> @franva you do not need a deleteHash to add to an album. You simply need to supply the album hash when calling upload:
> 
> ```
> ...
> const album = 'your-album-hash'
> imgur.upload({ image, album })
> ```

finally figured out. All good now.

Thank you

**Comment by KenEucker** [comment]
We've confirmed that it is possible to get the deletehash. I am closing this ticket.
