### ISSUE TITLE
How to add images to an album

### ISSUE THREAD

**Issue by franva** [KenEucker/imgur#222]
Hi there,

I'm new to ImgUr library. Appreciated if someone could give me a hand on 
adding images to an album.

Thank you.

**Comment by franva** [comment]
Got the answer.

https://stackoverflow.com/questions/77889717/how-to-add-an-uploaded-image-to-my-own-imgur-album

**Comment by KenEucker** [comment]
@franva my apologies, I don't know why I didn't see this ticket sooner. What was your solution?

**Comment by franva** [comment]
> @franva my apologies, I don't know why I didn't see this ticket sooner. What was your solution?

Hi Ken, all good man. 
I have posted my solution in that SOF link.
